global using NUnit.Framework;
global using Microsoft.Extensions.Options;
global using Moq;
global using Newtonsoft.Json;
global using RestSharp;
global using System;
global using System.Net;
global using test1.Models;
global using test1.Models.API;